# Generated by Django 2.0.5 on 2018-06-25 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('redditapp', '0004_auto_20180625_2051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='subreddit',
            name='posts',
        ),
        migrations.AddField(
            model_name='comment',
            name='parent_post',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='redditapp.Post'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='subreddit',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='redditapp.Subreddit'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='parent_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='redditapp.Comment'),
        ),
        migrations.RemoveField(
            model_name='subreddit',
            name='moderators',
        ),
        migrations.AddField(
            model_name='subreddit',
            name='moderators',
            field=models.ManyToManyField(related_name='moderates', to='redditapp.Profile'),
        ),
        migrations.AlterField(
            model_name='subreddit',
            name='owner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='subreddits', to='redditapp.Profile'),
        ),
        migrations.RemoveField(
            model_name='subreddit',
            name='subscribers',
        ),
        migrations.AddField(
            model_name='subreddit',
            name='subscribers',
            field=models.ManyToManyField(related_name='subscriptions', to='redditapp.Profile'),
        ),
    ]
