# Generated by Django 2.0.5 on 2018-06-25 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redditapp', '0005_auto_20180625_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subreddit',
            name='moderators',
            field=models.ManyToManyField(blank=True, related_name='moderates', to='redditapp.Profile'),
        ),
        migrations.AlterField(
            model_name='subreddit',
            name='subscribers',
            field=models.ManyToManyField(blank=True, related_name='subscriptions', to='redditapp.Profile'),
        ),
    ]
