# Generated by Django 2.0.5 on 2018-06-25 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('redditapp', '0006_auto_20180625_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subreddit',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='subreddits', to='redditapp.Profile'),
        ),
    ]
