# Generated by Django 2.0.5 on 2018-06-28 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('redditapp', '0008_auto_20180626_0058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='username',
        ),
    ]
