# Generated by Django 2.0.5 on 2018-07-12 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('redditapp', '0012_auto_20180710_1223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='owner',
            new_name='profile',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='owner',
            new_name='profile',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='owner',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='subreddit',
            old_name='owner',
            new_name='profile',
        ),
    ]
