# Generated by Django 2.0.5 on 2018-07-17 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redditapp', '0013_auto_20180712_1911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subreddit',
            name='title',
        ),
        migrations.AddField(
            model_name='subreddit',
            name='rules',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
