# Generated by Django 2.0.5 on 2018-07-19 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('redditapp', '0014_auto_20180717_1558'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subreddit',
            unique_together={('name',)},
        ),
    ]
