# Generated by Django 2.0.5 on 2018-07-20 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('redditapp', '0015_auto_20180720_0024'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='profile',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='profile',
            name='username',
        ),
    ]
