# Generated by Django 2.0.5 on 2018-07-21 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('redditapp', '0017_auto_20180721_0133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='votes',
        ),
        migrations.RemoveField(
            model_name='post',
            name='votes',
        ),
        migrations.AddField(
            model_name='comment',
            name='downvotes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='downvoted_comments', to='redditapp.Profile'),
        ),
        migrations.AddField(
            model_name='comment',
            name='upvotes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='upvoted_comments', to='redditapp.Profile'),
        ),
        migrations.AddField(
            model_name='post',
            name='downvotes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='downvoted_posts', to='redditapp.Profile'),
        ),
        migrations.AddField(
            model_name='post',
            name='upvotes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='upvoted_posts', to='redditapp.Profile'),
        ),
    ]
